### ISSUE TITLE
Вываливать на экран все поле крайней плохая идея, оно не влезает

### ISSUE THREAD

**Issue by finomen** [qurbonzoda/ProgLangsCpp#2]

**Comment by qurbonzoda** [comment]
Что предлагаете? Выводить координаты заселенных клеток?

**Comment by finomen** [comment]
Двигать окно просмтора по полю

2015-03-26 0:16 GMT+03:00 qurbonzoda notifications@github.com:

> Что предлагаете? Выводить координаты заселенных клеток?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/qurbonzoda/ProgLangsCpp/issues/2#issuecomment-86220774
> .

## 

Best wishes.
Nikolay Filchenko

**Comment by qurbonzoda** [comment]
Понятно, теперь можно двигать окно просмотра(20 x 20) по полю.
