### ISSUE TITLE
Реализация должна быть в cpp

### ISSUE THREAD

**Issue by finomen** [qurbonzoda/ProgLangsCpp#3]

**Comment by qurbonzoda** [comment]
программу на одном файле .cpp написать?

**Comment by finomen** [comment]
Обявления метов в h, определения в cpp.

**Comment by qurbonzoda** [comment]
Теперь все методы реализованы в main.cpp. Напишите пожалуйста если есть какие-то замечания или недочеты.

**Comment by finomen** [comment]
реализация методовЭ, объявленных в field.h в field.cpp, cell.h в cell.cpp
итд, было же в презентации

30 марта 2015 г., 16:52 пользователь qurbonzoda notifications@github.com
написал:

> Теперь все методы реализованы в main.cpp. Напишите пожалуйста если есть
> какие-то замечания или недочеты.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/qurbonzoda/ProgLangsCpp/issues/3#issuecomment-87688260
> .

## 

Best wishes.
Nikolay Filchenko

**Comment by qurbonzoda** [comment]
исправил
